markdown        : redcarpet
pygments        : true
contact         : "info@software-carpentry.org"
github_url      : "https://github.com/swcarpentry"
rss_url         : "http://software-carpentry.org/feed.xml"
swc_prefix      : "http://software-carpentry.org"
twitter_name    : "@swcarpentry"
twitter_url     : "https://twitter.com/swcarpentry"
exclude         : [branding, data]
